#!/usr/bin/env ruby

require 'quick_utils'

QuickUtils::TaskManager.run("app_cron") do |config|
  config.root_dir = Dir.pwd
  config.load_rails = true

  config.add_task 1, :hour do |mgr|
    SiteNotification.send_activity
  end

  config.add_task 3, :seconds do |mgr|
    Job.process_ready_jobs(environment: config[:environment], break_if: lambda { mgr.state != :running })
  end

end
