### Generated by SchemaSync
class SchemaSyncAjpnk < ActiveRecord::Migration
	def change
		create_table :recipes
		add_column :recipes, :title, :string
		add_column :recipes, :yield, :string
		add_column :recipes, :description, :string
		add_column :recipes, :ingredients, :string
		add_column :recipes, :directions, :string
		add_column :recipes, :tags, :string, {:array=>true}
		add_column :recipes, :created_at, :datetime
		add_column :recipes, :updated_at, :datetime
	end
end