### Generated by SchemaSync
class SchemaSyncZjcya < ActiveRecord::Migration
	def change
		create_table :followings
		add_column :followings, :follower_id, :integer
		add_column :followings, :user_id, :integer
		add_column :followings, :created_at, :datetime
		add_column :followings, :updated_at, :datetime
	end
end