### Generated by SchemaSync
class SchemaSyncOsnav < ActiveRecord::Migration
	def change
		add_column :users, :notification_frequency, :integer, {:default=>1}
		add_column :users, :last_notification_at, :datetime
	end
end