### Generated by SchemaSync
class SchemaSyncCfetx < ActiveRecord::Migration
	def change
		add_column :recipes, :yield_count, :integer
		add_column :recipes, :preparation_time, :integer
		remove_column :recipes, :yield
	end
end