### Generated by SchemaSync
class SchemaSyncNvadj < ActiveRecord::Migration
	def change
		create_table :invoices
		add_column :dishes, :feature_id, :integer
		add_column :features, :creator_id, :integer
		add_column :invoices, :ending_at, :datetime
		add_column :invoices, :total, :integer
		add_column :invoices, :amount_due, :integer
		add_column :invoices, :stripe_charge_ids, :string, {:array=>true}
		add_column :invoices, :charged_at, :datetime
		add_column :invoices, :user_id, :integer
	end
end