### Generated by SchemaSync
class SchemaSyncSiypc < ActiveRecord::Migration
	def change
		create_table :photos
		add_column :dishes, :primary_photo_id, :integer
		add_column :photos, :dish_id, :integer
		add_column :photos, :comment_id, :integer
		add_column :photos, :image, :jsonb
		add_column :photos, :created_at, :datetime
		add_column :photos, :updated_at, :datetime
	end
end