### Generated by SchemaSync
class SchemaSyncKpohe < ActiveRecord::Migration
	def change
		add_column :features, :processing_started_at, :datetime
		add_column :features, :processing_id, :string
		add_column :invoices, :amount_paid, :integer
		add_column :invoices, :finalized_at, :datetime
		add_column :invoices, :processing_started_at, :datetime
		add_column :invoices, :processing_id, :string
		add_index :features, [:processing_started_at]
		add_index :invoices, [:processing_started_at]
	end
end