### Generated by SchemaSync
class SchemaSyncIlnzo < ActiveRecord::Migration
	def change
		add_column :dishes, :processing_started_at, :datetime
		add_column :dishes, :processing_id, :string
		add_column :dishes, :meta_graph_updated_at, :datetime
		add_column :dishes, :meta_updated_at, :datetime
		add_column :dishes, :meta, :jsonb
		add_column :users, :processing_started_at, :datetime
		add_column :users, :processing_id, :string
		add_column :users, :meta_graph_updated_at, :datetime
		add_column :users, :meta_updated_at, :datetime
		add_column :users, :meta, :jsonb
		add_index :dishes, [:processing_started_at]
		add_index :dishes, [:meta_graph_updated_at]
		add_index :dishes, [:meta_updated_at]
		add_index :users, [:processing_started_at]
		add_index :users, [:meta_graph_updated_at]
		add_index :users, [:meta_updated_at]
	end
end