### Generated by SchemaSync
class SchemaSyncCshgz < ActiveRecord::Migration
	def change
		add_column :users, :cached_chefscore, :integer
		add_column :users, :cached_dishes_count, :integer
		add_column :users, :cached_followers_count, :integer
		add_column :users, :cached_followings_count, :integer
	end
end