### Generated by SchemaSync
class SchemaSyncTldkz < ActiveRecord::Migration
	def change
		create_table :features
		add_column :dishes, :is_feature_autorenewable, :boolean, {:default=>true}
		add_column :features, :start_time, :datetime
		add_column :features, :end_time, :datetime
		add_column :features, :base_price, :integer
		add_column :features, :billable_amount, :integer
		add_column :features, :is_cancelled, :boolean
		add_column :features, :cancelled_at, :datetime
		add_column :features, :finalized_at, :datetime
		add_column :features, :dish_id, :integer
		add_column :features, :invoice_id, :integer
	end
end