### Generated by SchemaSync
class SchemaSyncXkitg < ActiveRecord::Migration
	def change
		rename_column :recipes, :yield_count, :serving_size
		add_column :recipes, :prep_time, :string
		remove_column :recipes, :preparation_time
	end
end