### Generated by SchemaSync
class SchemaSyncXjduv < ActiveRecord::Migration
	def change
		add_column :dishes, :state, :integer, {:default=>1}
		add_column :dishes, :state_changed_at, :datetime
	end
end