### Generated by SchemaSync
class SchemaSyncCaghn < ActiveRecord::Migration
	def change
		create_table :app_events
		add_column :app_events, :action, :string
		add_column :app_events, :actor_id, :integer
		add_column :app_events, :recipe_id, :integer
		add_column :app_events, :comment_id, :integer
		add_column :app_events, :user_id, :integer
		add_column :app_events, :meta, :jsonb, {:default=>"{}"}
		add_column :app_events, :created_at, :datetime
		add_column :app_events, :updated_at, :datetime
		remove_column :recipes, :prep_time
	end
end