### Generated by SchemaSync
class SchemaSyncYgxki < ActiveRecord::Migration
	def change
		add_column :dishes, :description_html, :string
		add_column :dishes, :directions_html, :string
		add_column :dishes, :purchase_info_html, :string
	end
end