### Generated by SchemaSync
class SchemaSyncUcozn < ActiveRecord::Migration
	def change
		create_table :locations
		add_column :locations, :place_type, :integer
		add_column :locations, :city, :string
		add_column :locations, :admin, :string
		add_column :locations, :country, :string
		add_column :locations, :country_iso2, :string
		add_column :locations, :latitude, :decimal
		add_column :locations, :longitude, :decimal
		add_column :locations, :postal_code, :string
		add_column :locations, :population, :integer
		add_column :locations, :created_at, :datetime
		add_column :locations, :updated_at, :datetime
	end
end